stages:
  data_injection:
    cmd: python src/data_injection.py
    deps:
      - data/raw/diabetes_prediction_dataset.csv
    outs:
      - data/processed/preprocessed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed/preprocessed_data.csv
    outs:
      - data/processed/final_data.csv

  visualization:
    cmd: python src/visualization.py
    deps:
      - data/processed/final_data.csv

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/processed/final_data.csv

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - data/processed/final_data.csv
    outs:
      - metrics/random_forest_metrics.csv
      - models/rf_model.joblib
