# params.yaml

# Data parameters
data:
  raw_path: data/raw/diabetes_prediction_dataset.csv
  processed_path: data/processed/final_data.csv

# Model parameters
model:
  type: RandomForestClassifier
  random_state: 42
  test_size: 0.2
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1

# Output paths
output:
  model: models/rf_model.joblib
  metrics: metrics/random_forest_metrics.csv
